FROM clux/muslrust:stable

ENV DEBIAN_FRONTEND="noninteractive"
ENV JAVA_VERSION="11"
ENV ANDROID_TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip"
ENV ANDROID_VERSION="29"
ENV ANDROID_BUILD_TOOLS_VERSION="29.0.3"
ENV ANDROID_ARCHITECTURE="x86_64"
ENV ANDROID_SDK_ROOT="/usr/local/android-sdk"
ENV FLUTTER_CHANNEL="stable"
ENV FLUTTER_VERSION="3.0.2"
ENV GRADLE_VERSION="7.2"
ENV GRADLE_USER_HOME="/opt/gradle"
ENV GRADLE_URL="https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip"
ENV FLUTTER_URL="https://storage.googleapis.com/flutter_infra_release/releases/$FLUTTER_CHANNEL/linux/flutter_linux_$FLUTTER_VERSION-$FLUTTER_CHANNEL.tar.xz"
ENV FLUTTER_ROOT="/opt/flutter"
ENV PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/platforms:$FLUTTER_ROOT/bin:$GRADLE_USER_HOME/bin:$PATH"

# Install the necessary dependencies.
RUN apt-get update \
  && apt-get install --yes --no-install-recommends \
    openjdk-$JAVA_VERSION-jdk \
    curl \
    unzip \
    sed \
    git \
    bash \
    xz-utils \
    libglvnd0 \
    ssh \
    xauth \
    x11-xserver-utils \
    libpulse0 \
    libxcomposite1 \
    libgl1-mesa-glx \
    wget \
    nano \
  && rm -rf /var/lib/{apt,dpkg,cache,log}

# Install Gradle.
RUN curl -L $GRADLE_URL -o gradle-$GRADLE_VERSION-bin.zip \
  && apt-get install -y unzip \
  && unzip gradle-$GRADLE_VERSION-bin.zip \
  && mv gradle-$GRADLE_VERSION $GRADLE_USER_HOME \
  && rm gradle-$GRADLE_VERSION-bin.zip

# Install the Android SDK.
# RUN mkdir /root/.android \
#   && touch /root/.android/repositories.cfg \
#   && mkdir -p $ANDROID_SDK_ROOT \
#   && curl -o android_tools.zip $ANDROID_TOOLS_URL \
#   && unzip -qq -d "$ANDROID_SDK_ROOT" android_tools.zip \
#   && rm android_tools.zip \
#   && mv $ANDROID_SDK_ROOT/cmdline-tools $ANDROID_SDK_ROOT/latest \
#   && mkdir -p $ANDROID_SDK_ROOT/cmdline-tools \
#   && mv $ANDROID_SDK_ROOT/latest $ANDROID_SDK_ROOT/cmdline-tools/latest \
#   && yes "y" | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS_VERSION" \
#   && yes "y" | sdkmanager "platforms;android-$ANDROID_VERSION" \
#   && yes "y" | sdkmanager "platform-tools"


#   && yes "y" | sdkmanager "system-images" \
#   && yes "y" | sdkmanager "android-29" \
#   && yes "y" | sdkmanager "google_apis" \
#   && yes "y" | sdkmanager "build-tools" \
#   && yes "y" | sdkmanager "ndk"
#   && yes "y" | sdkmanager "cmdline-tools;latest"


  ##ANDROID SDK AND NDK which 
# RUN cd $HOME \
# && wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip \
# && unzip sdk-tools-linux-4333796.zip -d Android \
# && rm sdk-tools-linux-4333796.zip \
# && wget https://dl.google.com/android/repository/commandlinetools-linux-6200805_latest.zip \
# && unzip commandlinetools-linux-6200805_latest.zip -d Android/cmdline-tools \
# && rm commandlinetools-linux-6200805_latest.zip \
# && echo 'export ANDROID_SDK_ROOT=$HOME/Android' >> $HOME/.bashrc \
# && echo 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64' >> $HOME/.bashrc \
# && echo 'export PATH=$ANDROID_SDK_ROOT/cmdline-tools/tools/bin:"$PATH"' >> $HOME/.bashrc \
# && echo 'export PATH=$ANDROID_SDK_ROOT/cmdline-tools/tools/lib:"$PATH"' >> $HOME/.bashrc \
# && echo 'export PATH=$ANDROID_SDK_ROOT/tools:"$PATH"' >> $HOME/.bashrc \
# && echo 'export PATH=$JAVA_HOME/bin:"$PATH"' >> $HOME/.bashrc \
# && . $HOME/.bashrc \
# && sdkmanager --sdk_root=$ANDROID_SDK_ROOT --install "system-images;android-29;google_apis;x86" "system-images;android-29;google_apis;x86_64" "platform-tools" "platforms;android-29" "build-tools;29.0.3" "ndk;22.0.7026061" "cmdline-tools;latest" \
# && sdkmanager --licenses

# Install Flutter.
RUN curl -o flutter.tar.xz $FLUTTER_URL \
  && mkdir -p $FLUTTER_ROOT \
  && tar xf flutter.tar.xz -C /opt/ \
  && rm flutter.tar.xz \
  && git config --global --add safe.directory /opt/flutter \
  && flutter config --no-analytics \
  && flutter precache \
  && yes "y" | flutter doctor --android-licenses \
  && flutter doctor \
  && flutter update-packages

# wasm-pack (Required for both WEB targets) 
# RUN curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

# binaryen
# To build Credible for WEB using ASM.js you will need binaryen, which allows the conversion of DIDKit WASM to ASM.js. This is necessary when you don't have WASM support and need to run your page in pure Javascript. More detailed instructions on how to build binaryen can be found here.

# If you are in a UNIX-like distribution you just have to clone the repo and build, we recommend cloning into your ${HOME}, to avoid having to specify the ${BINARYEN_ROOT} variable:

# $ git clone https://github.com/WebAssembly/binaryen ~/binaryen
# $ cd ~/binaryen
# $ cmake . && make

